language: go
go:
- 1.9.x
- 1.10.x
- 1.11.x
install: make bootstrap
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
deploy:
- provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
    repo: manifoldco/terraform-provider-manifold
env:
  global:
  - MANIFOLD_TEAM=manifold-integration-ci
  - TF_ACC=true
  - AWS_REGION=us-east-1
  # MANIFOLD_API_TOKEN
  - secure: GKSMcHSZ1O1AUscaTb8nHVT1pO9jFpFeKQke6DjD0Bz2l+/0/5NHb/JHKRunGZJkD9lTUatj0IuqAMlxbzIasL313vgg9+pmqn8APV3/L0/h2P97gNBy0RZs0uMM5Feuy0jN78MnWkRm8Zo237T8hI035xwESeTde13/ygB9IUJnWs0OsPTFssOiBMyoneqduLKzSIrId88q1Zof8f2x4uQbPfhuCNHiAiRYKR0lAEVS/9QqtHHzsX6nOVY4bvNnzvZm6VTIpmASar5qShGmpC5L1bqXZB8d11FIs8FGFOwd2LlTmdukFy9xz0TJD7xSxQMOV7k1bzn/4RHylBuEFOJ939WexFi3QmK2u+xE9u6eh4KtZWONAVIMaR3qAF24VFVBreCwpv/qeSn3NTp69gucBAXwvLXSNmxbTE3epQFQRolgNIQXa8WP/hlG+7YE5rfurnLuA9USSEV9DcQDjyCxqOb941fpxbiiJw2CNz6jSsme8zE860XUnSIz1KXfucqaUXKLjAoSKVTs1opZ+o2eg4jmkLp5APIVBSejqXUKL37q3ru/aWSYLHz+4QMx6dEKpWKDurPXUkKiwQVJRrOz+gCxxKsvMM2gR6JiPf9sHBgs5D4kMXcP5Z/T/f0Ut8aNCu1hUhboyeUjjUDAJp3Ma3rfntWhndIy4J7q1Mo=
  # AWS_ACCESS_KEY_ID
  - secure: D788IIYKZK0Azj6vqFwCnMbJW/lEUsP7K/P8Avq7B2kN1i07PaLIPeFcL8+/VlnNC3IEXeqWP6x1ONGkFre3rLN++YXhoFuvXOt+4GVOMOURDnm/sedmnSOnvWPT677TSmlWMyGXB97hhHI/rVgJ2A10dMGUZQKYnKrYtUsKlWl1dmbqhfMJ4F/VJawhBMalasdM6JF7TRojUO3U04wa0AXupcHqJO5DnSby7rFl6D95+At3QVpfI97L6jwY8z2ea5d+o/3nTltzjOCwFXQbfD8mIbRL/1hFX8uC1Mq6JkdJLUpPHGydO1bV9c/WPVGwd/9HQSjOJqpsVfkTqZogU9ifMvxNQMDu4YitTFXov1kFm7tZIxXhFpHsJPm7xxlRn2nDlDjkECLHG42XddVKVRMtfKFS715ufxYXMI+c0b9XmOXYCAsozgBLGjC2miQwg7foQoAmz7XIwg6lxYkOkAEnC3BtVK0fYI0Ezcbbk+geX5gIktr7TXD6VgCWo8eq9xQVqQXopPU03f6qAOfNZzexWJR/O55ST7xnHXg5mrnj3rFoW6QOjydkPtdey0UvgUNGCWJmCyqSoNemSxRx1eWMOLYA0SVnfEDY9l1ZcQ5KjnVvDsuLbpnawSTx2go4LakWP/owAiwpXmfZ+6oEnw5nFaCpK592HswMInDgXtQ=
  # AWS_SECRET_ACCESS_KEY
  - secure: Sxx4drDGcl+u8LMh3I8g4qpCxYelSXHuwRsFSbQhp9C+eD0He6gorA8N5IFGBU1nYQfDUF+BhudKs8SRLhC4OL7OyGVtExFq35k7NDMR0ierJH7seKWbCqpJ421p+M0+3TVER/aNnlP/ZtlcvkCJE4sFbRnzaZVIeT++Mh01eVaaTSjG9YzAexo/ski/r9DNQVEHJhmj9FQdepES/r8a39nTEshiD/CimVbTj57lTAl56+DuERsQ9T8k+bjhAlaTqmOOs4v9HXDP09OgEAbLAgxh4f0YscNIFMy9LQR/FyrOfzWR6CjP3OeS5fr0dqqLuf/cGQ01zfmno59aKCJulrw3kKEW9Jksu5xRhHeC4K2KlRRIuTSHKLKVSA3QWf1UjdZYmhhQIrH2ea7nnBp7FWJ9DTLJVdqPmvdkavG5ubHhoDFm924d8v1yka/qu7JCCWcZLJWdZa6Jw41Bi2z/w3nbdBc7NQaio4ZH+cR+lnTI/jYsMteulUGV9QpdD5DGmj3QFv4SO6TJIw34g9r0cZb2spdbH2g1ud3WAg2sjN+mHJkHhJFZf4rxbCHc75QcXECD37jBhFQMXTI9nGJ7L2SZ4sSPCVwyOhZIFvzE2NF9D9QxtKedZQCb+FeYYi/BVAKf0mhYWkPqNCHRKu1w3zdQUpiNLGsGHBOdey41M1s=
  # GITHUB_TOKEN
  - secure: KEeEOrN5AnypX5pAXkz8AfvaXC/sVTikU77FKxdV+VVOXKxNGgsbIlbnek8fufWTpAxPoLWjFsde05Cc3EaSuoaXfUy8Yv8Q+smBfjk9n0aVbEB+pOEy6VHnd+zzt5k2LwtKxlxYZaecdROT3nReyHETLky0cOoho06DtW6/lgqGvoiyzKqxLf7XanAbnE5eMFmymC40akz1w9DFEM2kZz9JyGOwVJnjBNHEE5p/Jx9RV36TY50losppTqzf3iuoDYDiI5UGS6puIzw5QJFQrX42IJl3LU3oilDrNTvwsoJH7eg4iiI/PYuNRcCwaNFNKteY27FWog+zzQeq9x5AsMiqfAlENDsSfmqx8EE+hCBFcr/FBr1Nsx4H2n802tCFG67bRS7ExkzWcZQKXHKyApSHFMmSVf5NCEGoiArYVgHYhsT1ZJK6FHghd0y4Dnv9SIQwtZ+zLKjixYy4+V9OWy5sA6t2c2wG8N/GBOlNJmJyKQs3iwUJhXqFfzwV4QhS3DOu8XC9bA99r97/hdWC9OW+qzy1FqWW6DwCQOp6YU/wcuu8sq0Vg6hkNVm52ZIgRzqCCP+aLtUZ1cNPNdnAyEXqwNQeNFNO8HlgrWjP7RZKVjlLnqdXJiA1CdisjYgIJ5p7DyLr4KSVx2kUy8a6ivUMIgxhPWjVlZ05IKV7CuA=
after_success:
  # only report coverage for go-version 1.11
  - if [[ $TRAVIS_GO_VERSION =~ ^1\.11 ]] ; then bash <(curl -s https://codecov.io/bash) -f all-cover.txt; fi
